{% set version = "4.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggmap/ggmap_{{ version }}.tar.gz
  sha256: 0de639357c066e3b632eb960fd811276558ce29aefa2f77ef711ff5841c734f5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rgooglemaps
    - r-bitops
    - r-digest
    - r-dplyr
    - r-ggplot2 >=2.2.0
    - r-glue
    - r-httr
    - r-jpeg
    - r-magrittr
    - r-plyr
    - r-png
    - r-purrr
    - r-rjson
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-rgooglemaps
    - r-bitops
    - r-digest
    - r-dplyr
    - r-ggplot2 >=2.2.0
    - r-glue
    - r-httr
    - r-jpeg
    - r-magrittr
    - r-plyr
    - r-png
    - r-purrr
    - r-rjson
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('ggmap')"           # [not win]
    - "\"%R%\" -e \"library('ggmap')\""  # [win]

about:
  home: https://github.com/dkahle/ggmap
  license: GPL-2.0-only
  summary: A collection of functions to visualize spatial data and models on top of static maps from various online sources (e.g Google Maps and Stamen Maps). It includes tools common to those tasks, including functions for geolocation and routing.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - druvus

# Package: ggmap
# Version: 3.0.0
# Title: Spatial Visualization with ggplot2
# Description: A collection of functions to visualize spatial data and models on top of static maps from various online sources (e.g Google Maps and Stamen Maps). It includes tools common to those tasks, including functions for geolocation and routing.
# URL: https://github.com/dkahle/ggmap
# BugReports: https://github.com/dkahle/ggmap/issues
# Authors@R: c(person("David", "Kahle", email = "david.kahle@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-9999-1558")), person("Hadley", "Wickham", email = "h.wickham@gmail.com", role = "aut", comment = c(ORCID = "0000-0003-4757-117X")), person("Scott", "Jackson", email = "scottmmjackson@gmail.com", role = "aut"), person("Mikko", "Korpela", email = "mvkorpel@iki.fi", role = "ctb"))
# Depends: R (>= 3.1.0), ggplot2 (>= 2.2.0)
# Imports: RgoogleMaps, png, plyr, rjson, jpeg, digest, scales, dplyr, bitops, grid, glue, httr, stringr, purrr, magrittr, tibble, tidyr
# Suggests: MASS, hexbin, testthat
# License: GPL-2
# LazyData: true
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-02-05 09:19:03 UTC; ligges
# Author: David Kahle [aut, cre] (<https://orcid.org/0000-0002-9999-1558>), Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>), Scott Jackson [aut], Mikko Korpela [ctb]
# Maintainer: David Kahle <david.kahle@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-05 10:19:04
