# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "L6g/ooIMFfLjDYY9PCBM39eggyzU65S8j1GxDiaN2ACUiGE+PV9UzW/DNg5fllEK/1CNqfpTAlJar2+BqLk9dxHF5r2sZ3063Cf6Dbn9sxAIJFMLQbjQLx/7AFWr3a0iNR1pP728BMoFT/yWgQ63cFTGoco5ei8eLGl03+jop+fRog31mWqiXvaeY0HGG9P2F3AOgSl1uvsJTPoBh2vI/mOh1DecaIbDLktydzlzYQ5/y3n+YC9f40U7kYotdygPYOq7RwxaP7AEiQjc8zgUCevid2F0uA1vA7E6qH/REgONEyWjKH3z6LB6JXNCSuSo1jQpurVUo4xNz+vHjUGXYJRV5shRTMSk28FGnj8C689/X6sz75zihbY62Ays0JvfJiaeTkSA/82Jgb2O8SvzN6XD3WiGxzcUYnfmEVU7w/1AhDGLk1gyDlcmrr3m8x8Z4iVEoRSnQPa6lbENhEjeH23NIYKjYpYY4B6MHP1P8yIBJ1UOfRQzIiYYeJMoBpUM44eJWRY1VJt0MlOPj0Q5dEBJmJJC2BGiLjvciHznmNonKKQnWQ3QlaNDfETIyW6oilvqg4PGm8+Vn5EDhVEUn/83tECcg64zSxl+luarjZyeP5F23COfId6BZJif6siwPzZ8k0niYNhj2iXuULqbbjs8UL9ZjD6DavqAx5JJ8mw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
