travis:
  secure:
    BINSTAR_TOKEN: Vg/jKy8pJrhTjeuaQb3Y44SMIZLVWylSXqdfKWN4kSP3AeAacy3Ml5stGyfAJIu3lHrKZ4zzXAR3osPoAEJHzLX5SQvZQHWDj+D4mKABMHWU5UxitYQ3Agb8DkUdcWzcgB0TzeqMhSLxa+9qIGBeX3a8/+617BPB8RPCznQfyEbOtQmavDbryWNh38/9RK/aY+ta4bLePFlLKQ8eqU8N4osBOlE0CzKSXt8i69LyzTPC5ZnDE1LBoOituRG1WsWUcHFAqn1mLhI0omyJsUda1qgM/EsF7EImdpyf8CLFJ0w3FcIe2mMWR1TvYb+Lx6zUDVWxgJbfRoND3uDRMaYpOAl/erw7l9PHXXG3Ce8rWMBSI+rS7IOjgRvuEjB6GuPESwBL5wsaePn2bdnfbn+2Xlb5SSdef8vFt7RnP9RZv2ptPr/IEckiseYUbRJr7AY08EDaqWnlSZp+G3q05VjSXc2OEf1u1ptWEwu7ivRa3OxzCWeA2bEhm6LF1aDVcB7H4e9v8z1FHW+jFOIvask+p/w/CdbWgXdTb4zWYfboFd5dJ7LCGxWgAZ0PtYsE9xo6e+nsItEXqWjIEFggzF+qzjCzfMLZfQvwkNkXwgDZ6xrtOjHrbPkoDkonStZx6iJnWpfKcJJqNj7qCI3sUHmhuJRMEvOQCWsQXB++G21WXsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
