travis:
  secure:
    BINSTAR_TOKEN: RQPRq7+3qKRohX60Cy4TfiACYnXxGshxMMZdRUdB4YoH11MJeiMrXUH6O1ti+37Zv7QGPx9MyIQjDkNuaonYCaLGiXnESnxBo9D28dbIB84w648NOPJOOLobbsW6yGHQWGptrd5FsGtTwPUUNEdxL7uIaYzWASVWwRRn2+nOzMXp2pwWyv0cC/6qTTimjAxlF69rYAc3BaFqSZ+grimXVigVEgDrOD7j3tKjC3c/sQb0YglcMqKB8cfsfIwjL/25ZsAiDaSf+4116/J+Wn9HN35pGQd3hbepA3VYA4sQYx9Hj393L+V/RSiqCNfxKsD/HYzqatvwiv1S8JuUhXi07kdRUjLacy4XR3d1XjHSXCgqt/7kAM4tF4OZN7gW9B1XN2jDTkdQ0fmps+GaP8y14cTHUMo0Xa6Qs58YbLEf6GGh8Tz4lK7bGir/p0bfsmz383rdtKU7+AhJ3M+kqh9Ul789C3oAGWq3FsicMP7ALhIICaewpcE/MSUxUHUC2AGi8IZT0Rt580RMZy6u0y7qG3fuV7eD63tJEbt+vRg13FK/q3AP2mYvfTD/V2RMOSs43PGQAfOy6WnXyDfpHBqsXByiVxVd31hztiNMYX1pa36qNWAQp5hDYTUxSxdPz9BaViWpOWAjUp9sZKMEqhxVBSMapwS04+Vn5oEcJmwo168=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
