travis:
  secure:
    BINSTAR_TOKEN: eO/9x/53WeTxxalrKOVTG1qLjJ2dR3ZBRVqBk9xM+bq2Pu7RzjX/jAEtZT9HIzfa0ps2xXjqtcoVz3+4wWcVcsb5OiBrGQhqxJ4bIq+1RHqI+uerI3zVZ0SwUKhRXYvKx6tg24vl7T9XYZY6riYZf2mlizUqrUhz0Ox8DhL9CeJUCimstVQsthEhDcLTUuTJkJdCZ5PTgZ1b//n5s3OLgx2mVBsK2Qgijj6pf4o5lbS2W80olRa4QZykty8FQqwNtOYfRdqIu66OyjyJa5jZgoVF3CPFzquUXTQaQNtSFce1TozI1nKp1Hmw+OuWsYoVXUG6cCGQ9vBlOW3rK3EzLb2z47qC9V09EbbPzgkYufchEjCh6hTNz3+YbvMDdF1Cd3qfm4TFKiHO2F6A3JeidAFbwnN/7ayleFpIv/keUCGzpaL2KIpOHHEu4QpipnKU1ZlwIrrh83AKoC+fe8sGKYQ1UCRk/ZYkCfrtxNGpllsRnzSNdostzq/89b0+bfZpMEhEpIhqTAPSaOYhkeG3AfQruU9LDl6SGvzh/UDUCicACyQPOKXlbpL13BzJieNn59t4EIQWxFABUNZT6SEXwSswupyaPSH563EP82ZNYT9lxGLDq5sRKLIz1VnlxMjI3Lsr7tZsTgB0DZTKJDgQIjZqXxHhHOU1u5YAqF2lc+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
