travis:
  secure:
    BINSTAR_TOKEN: suycoAt8i/4fK9YfY+nTv6r+lLx6nSnd3tNfcW594ZMpGbGvHvpAWrEbjv3ol5gY/tb6c7GPeN4UKb3VfesC4lzxzN3uTT1YUr+pIOAkXlap2mMmX7KKdktkwrmiJZFZvXS3p52PVCGJvP6DkTFsnFOAIlnulWEcLfoi6f1XetkVB9f7fwkLazCidoXYddJrvdCeBSa1q1C/xLKW+EnxvOOsxACdOYcpwbycPZtLtUN4Ydm99d8Ov2hW1kpM0LO52BKAy55mZ8gEtiMYV3NFCrmnhViI1HfmyPKmHT3PZUW6TXTjkkx2oO+w/wtJmNzVYsPGELNCmQ9pBDgWdRmRN4zf5yNQb7NnxDLMU6regqijCnB4/8uIlQAjwe/zrdnoNmSQv74K0MVAESJDkvKCDTU7Dr40FkOqmYNka4KqoWd315F0Vg0bHA0IzDhnBIrXcBve1X/b/yi7GKM6yz9U36sJqqS53LdnFehRAUVZ10xeiuuvNoDyCNN2eFFXaZtKRD9roEedfAUUSaGyNM/gkI1id1r8e4SSZ+HQaQmC0ut/bLCO9qKGKyt1G4KHQl58wxE6P55m7agIVhCwI2F8MGtl4OASh51REFxAE35Z9lnIyGyPIJQYGhwdDOd0jggnLxqTz92w4v/HgHbmyuQIu7NwLCw7/9u5KcUQMXQgkS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
