appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: L6g/ooIMFfLjDYY9PCBM39eggyzU65S8j1GxDiaN2ACUiGE+PV9UzW/DNg5fllEK/1CNqfpTAlJar2+BqLk9dxHF5r2sZ3063Cf6Dbn9sxAIJFMLQbjQLx/7AFWr3a0iNR1pP728BMoFT/yWgQ63cFTGoco5ei8eLGl03+jop+fRog31mWqiXvaeY0HGG9P2F3AOgSl1uvsJTPoBh2vI/mOh1DecaIbDLktydzlzYQ5/y3n+YC9f40U7kYotdygPYOq7RwxaP7AEiQjc8zgUCevid2F0uA1vA7E6qH/REgONEyWjKH3z6LB6JXNCSuSo1jQpurVUo4xNz+vHjUGXYJRV5shRTMSk28FGnj8C689/X6sz75zihbY62Ays0JvfJiaeTkSA/82Jgb2O8SvzN6XD3WiGxzcUYnfmEVU7w/1AhDGLk1gyDlcmrr3m8x8Z4iVEoRSnQPa6lbENhEjeH23NIYKjYpYY4B6MHP1P8yIBJ1UOfRQzIiYYeJMoBpUM44eJWRY1VJt0MlOPj0Q5dEBJmJJC2BGiLjvciHznmNonKKQnWQ3QlaNDfETIyW6oilvqg4PGm8+Vn5EDhVEUn/83tECcg64zSxl+luarjZyeP5F23COfId6BZJif6siwPzZ8k0niYNhj2iXuULqbbjs8UL9ZjD6DavqAx5JJ8mw=
conda_forge_output_validation: true
