travis:
  secure:
    BINSTAR_TOKEN: ggkA/c5ScVtdm2388ISE3HnTMvcgUlrkL6Yscauc/mCIKI2Va+Rh7zI+OgbFTxQK0RMYjI3gc/NaSWbv1eG9uGyTUS3PNLJGrB9aIzuXl1d5tXZxBLZqii2mVq6ylEPiThYmc+02sNUcMnwzQEPB35qBYMhDoKbV/ckN3+uZg1SIS2ebSG4K6v9is2CZY1U2VyNdX10GxIY4HPCzb0BM5LFPpRsthAbfEWanuBtqQr+Ic988an8slT0wMv4sq1uUvtLyjjMaui1wLMZxvlyZ319mf2rbQySvmeZsdRPjzIktlLmVl+TGcqDGCCDDZAYIjnlkHmwHmmwBd2Dz0WrK18zyPdqlOBF9866xTfGR3w4/JfdzvHmiYPgI3VhJ8cIPjcRGILzARMaflJGiDysHb+Rt0BBtzCwK71ozkgkejIM61asXp8nwMGLahU6TVKUBsGNaiCKZ9CWT+j+fjzWvWbnG6+P2ME9Uy4wujsf6ywQymrGatd/X52qCXyLId8k5ZrdLaOJ3ICQPjNrigHRE5blh+AEs8/0IEH57WpGt0VkaW7l1GXys0kckYVohaskg5KRlpjA5iazEdwx5IFy2lhEgwshMEn5IEj3UNTXkpc7n4Ep8ZnzzmlZtyv4MK+bzlNXSZq5BNj6pmem0C6cJZIpUXxbBniQVvjNayDed8Go=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
